### ISSUE TITLE
Docker compose.yaml help

### ISSUE THREAD

**Issue by alanmilinovic** [akarazniewicz/stremio-jellyfin#2]
Can you write an example of how compose.yaml should look like please?

Thank you

**Comment by alanmilinovic** [comment]
Figure it out, maybe you can add it into documentation.

```
version: '3.5'
services:
  jellyfin-stremio-addon:
    image: ghcr.io/akarazniewicz/stremio-jellyfin:latest
    restart: 'unless-stopped'
    ports:
      - "60421:60421"
    environment:
      - JELLYFIN_USER=yyy
      - JELLYFIN_PASSWORD=xxx
      - JELLYFIN_SERVER=http://192.168.188.203:8096/
```
